version: 2
jobs:
  dependencies:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/TriviaWeb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/TriviaWeb
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/TriviaWeb
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build
          command: yarn build
  test:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/TriviaWeb
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Test
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
          command: yarn test --ci --testResultsProcessor="jest-junit"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
  lint:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/TriviaWeb
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint
          command: yarn lint --format junit -o reports/junit/js-lint-results.xml
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
  flow:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/TriviaWeb
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Flow
          command: yarn flow
workflows:
  version: 2
  pipeline:
    jobs:
      - dependencies
      - build:
          requires:
            - dependencies
      - test:
          requires:
            - dependencies
      - lint:
          requires:
            - dependencies
      - flow:
          requires:
            - dependencies
