version: 2
jobs:
  dependencies:
    docker:
      - image: node:8.0
    working_directory: ~/TriviaWeb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/TriviaWeb
  build:
    docker:
      - image: node:8.0
    working_directory: ~/TriviaWeb
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build
          command: yarn build
  test:
    docker:
      - image: node:8.0
    working_directory: ~/TriviaWeb
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Test
          command: yarn test
  lint:
    docker:
      - image: node:8.0
    working_directory: ~/TriviaWeb
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Lint
          command: yarn lint
  flow:
    docker:
      - image: node:8.0
    working_directory: ~/TriviaWeb
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Flow
          command: yarn flow
workflows:
  version: 2
  pipeline:
    jobs:
      - dependencies
      - build:
          requires:
            - dependencies
      - test:
          requires:
            - dependencies
      - lint:
          requires:
            - dependencies
      - flow:
          requires:
            - dependencies
